---

- name: "Restart {{ python_service_name }}"
  ansible.builtin.systemd_service:
    name: "{{ python_service_name }}"
    state: restarted
    daemon_reload: true
  ignore_errors: "{{ ansible_check_mode }}"
  when:
    - python_service_systemd_enable is defined
    - python_service_systemd_enable
