---

- name: "Install yay on ArchLinux"
  ansible.builtin.package:
    name: "yay"

- name: "Install useful packages on ArchLinux"
  become: true
  become_user: "{{ packages_aur_user }}"
  kewlfft.aur.aur:
    use: "yay"
    name: "{{ packages_merged_list }}"
  ignore_errors: "{{ ansible_check_mode }}"
