---

# Explicitly via set_fact to overwrite the content of previous runs of this role and to disallow overwriting it
- name: "Prepare variables that need to be reset or are disallowed to be overwritten with initial state"
  ansible.builtin.set_fact:
    python_service_config_arg: []
    python_service_handlers_to_notify: "{{ lookup('community.general.merge_variables', 'python_service_handlers_to_notify_', pattern_type='prefix') }}"
    python_service_systemd_service_options_base:
      Environment: "{{ lookup('community.general.merge_variables', 'python_service_systemd_service_environment_', pattern_type='prefix') }}"
      StateDirectory: "{{ python_service_name }}"
    python_service_systemd_service_options_config: {}

- name: "Assert that no mutually exclusive options for python requirements are given"
  ansible.builtin.assert:
    that: (lookup('ansible.builtin.varnames', '^python_service_requirements.*$', wantlist=true) | length) <= 1
    msg: "More than one of a list of packages, a local requirements file or a web URL to a requirements file is given, please choose one."

- name: "Ensure that user for the python service is created"
  ansible.builtin.user:
    name: "{{ python_service_name }}"
    create_home: false
    shell: "/usr/bin/nologin"
  register: python_service_user_info

- name: "Ensure that the state directory of the service exists"
  ansible.builtin.file:
    path: "/var/lib/{{ python_service_name }}"
    state: directory
    owner: "{{ python_service_user_info.uid }}"
    group: "{{ python_service_user_info.group }}"
    mode: 0755

- name: "Copy script"
  ansible.builtin.copy:
    src: "{{ python_service_script }}"
    dest: "{{ python_service_script_path }}"
    owner: "{{ python_service_user_info.uid }}"
    group: "{{ python_service_user_info.group }}"
    mode: 0750
  notify: "{{ python_service_handlers_to_notify }}"
  when:
    - python_service_script is defined
    - not python_service_script.startswith("https://")
    - lookup('ansible.builtin.fileglob', 'files/' + python_service_script) | length > 0

- name: "Template script"
  ansible.builtin.copy:
    src: "{{ python_service_script }}"
    dest: "{{ python_service_script_path }}"
    owner: "{{ python_service_user_info.uid }}"
    group: "{{ python_service_user_info.group }}"
    mode: 0750
  notify: "{{ python_service_handlers_to_notify }}"
  when:
    - python_service_script is defined
    - not python_service_script.startswith("https://")
    - lookup('ansible.builtin.fileglob', 'templates/' + python_service_script) | length > 0

- name: "Download python script from URL"
  when:
    - python_service_script is defined
    - "python_service_script.startswith('https://')"
  notify: "{{ python_service_handlers_to_notify }}"
  block:
    - name: "Set up request headers"
      ansible.builtin.set_fact:
        python_service_get_url_headers:
          Accept: application/vnd.github.raw
          Authorization: "token {{ python_service_github_read_token }}"
      when: python_service_github_read_token is defined

    - name: "Fetch script from web"
      ansible.builtin.get_url:
        url: "{{ python_service_script }}"
        headers: "{{ python_service_get_url_headers | default({}) }}"
        dest: "{{ python_service_script_path }}"
        owner: "{{ python_service_user_info.uid }}"
        group: "{{ python_service_user_info.group }}"
        mode: 0750
      ignore_errors: "{{ ansible_check_mode }}"

    - name: "Fetch requirements file from web"
      ansible.builtin.get_url:
        url: "{{ python_service_requirements_url }}"
        headers: "{{ python_service_get_url_headers | default({}) }}"
        dest: "/var/lib/{{ python_service_name }}/requirements.txt"
        owner: "{{ python_service_user_info.uid }}"
        group: "{{ python_service_user_info.group }}"
        mode: 0640
      ignore_errors: "{{ ansible_check_mode }}"
      when: python_service_requirements_url is defined

- name: "Clone git repository of python service"
  when:
    - python_service_git_repository_url is defined
    - lookup("ansible.builtin.varnames", "python_service_requirements.*") | length == 0
  block:
    # Systemd changes permissions of the directory which makes git cry
    - name: "Setup as safe directory"  # noqa: command-instead-of-module - Thats on purpose here, the git module has no way for setting a safe directory
      ansible.builtin.shell:
        executable: "/usr/bin/bash"
        cmd: |
          git config --global --add safe.directory /var/lib/{{ python_service_name }}/{{ python_service_name }}-repo
          git config --global --add safe.directory /var/lib/private/{{ python_service_name }}/{{ python_service_name }}-repo
      changed_when: false

    - name: "Clone git repository"
      ansible.builtin.git:
        repo: "{{ python_service_git_repository_url }}"
        dest: "/var/lib/{{ python_service_name }}/{{ python_service_name }}-repo"
        version: main
        update: true
      notify: "{{ python_service_handlers_to_notify }}"

- name: "Create venv using package list"
  ansible.builtin.include_role:
    name: poettig.roles.python_venv
  vars:
    python_venv_directory: "/var/lib/{{ python_service_name }}/venv"
    python_venv_modules: "{{ python_service_requirements }}"
    python_venv_handlers_to_notify: "{{ python_service_handlers_to_notify }}"
  when: python_service_requirements is defined

- name: "Copy requirements file from controller to remote"
  ansible.builtin.copy:
    src: "{{ python_service_requirements_file }}"
    dest: "/var/lib/{{ python_service_name }}/requirements.txt"
    mode: 0640
  when: python_service_requirements_file is defined

- name: "Create venv using requirements file copied or downloaded to remote"
  ansible.builtin.include_role:
    name: poettig.roles.python_venv
  vars:
    python_venv_directory: "/var/lib/{{ python_service_name }}/venv"
    python_venv_requirements_file: "/var/lib/{{ python_service_name }}/requirements.txt"
    python_venv_handlers_to_notify: "{{ python_service_handlers_to_notify }}"
  when: python_service_requirements_file is defined or python_service_requirements_url is defined

- name: "Create venv using requirements file from git repository"
  ansible.builtin.include_role:
    name: poettig.roles.python_venv
  vars:
    python_venv_directory: "/var/lib/{{ python_service_name }}/venv"
    python_venv_requirements_file: "/var/lib/{{ python_service_name }}/{{ python_service_name }}-repo/requirements.txt"
    python_venv_handlers_to_notify: "{{ python_service_handlers_to_notify }}"
  when:
    - python_service_git_repository_url is defined
    - python_service_requirements_file is not defined

- name: "Install configuration file if requested"
  when: python_service_config is defined
  block:
    - name: "Set config file name"
      ansible.builtin.set_fact:
        python_service_installed_config_filename: "{{ python_service_config | regex_replace('\\.(j2|jinja2?)$', '') }}"

    - name: "Create config directory"
      ansible.builtin.file:
        path: "/etc/{{ python_service_name }}"
        state: directory
        owner: "{{ python_service_user_info.uid }}"
        group: "{{ python_service_user_info.group }}"
        mode: 0755

    - name: "Install config"
      ansible.builtin.copy:
        src: "{{ python_service_config }}"
        dest: "/etc/{{ python_service_name }}/{{ python_service_installed_config_filename }}"
        owner: "{{ python_service_user_info.uid }}"
        group: "{{ python_service_user_info.group }}"
        mode: 0600
      notify: "{{ python_service_handlers_to_notify }}"
      when: lookup('ansible.builtin.fileglob', 'files/' + python_service_config) | length > 0

    - name: "Install config from template"
      ansible.builtin.template:
        src: "{{ python_service_config }}"
        dest: "/etc/{{ python_service_name }}/{{ python_service_installed_config_filename }}"
        owner: "{{ python_service_user_info.uid }}"
        group: "{{ python_service_user_info.group }}"
        mode: 0600
      notify: "{{ python_service_handlers_to_notify }}"
      when: lookup('ansible.builtin.fileglob', 'templates/' + python_service_config) | length > 0

    - name: "Set up variables necessary for configuration file"
      ansible.builtin.set_fact:
        python_service_systemd_service_options_config:
          ConfigurationDirectory: "{{ python_service_name }}"
          LoadCredential: "{{ python_service_installed_config_filename }}:/etc/{{ python_service_name }}/{{ python_service_installed_config_filename }}"
        python_service_config_arg:
          - "-c ${CREDENTIALS_DIRECTORY}/{{ python_service_installed_config_filename }}"

- name: "Prepare ExecStart as list of arguments"
  ansible.builtin.set_fact:
    python_service_execstart_args:
      - "/var/lib/{{ python_service_name }}/venv/bin/python3"
      - "{{ python_service_script_path }}"
      - "{{ python_service_script_args | default([]) }}"
      - "{{ python_service_config_arg }}"

- name: "Set ExecStart"
  ansible.builtin.set_fact:
    python_service_systemd_service_options_execstart:
      ExecStart: "{{ python_service_execstart_args | flatten | join(' ') }}"

- name: "Install systemd service"
  ansible.builtin.include_role:
    name: "systemd"
  vars:
    systemd_name: "{{ python_service_name }}"
    systemd_service_description: "{{ python_service_description }}"
    systemd_unit_options: "{{ lookup('community.general.merge_variables', 'python_service_systemd_unit_options_', pattern_type='prefix', override='warn') }}"
    systemd_service_options: "{{ lookup('community.general.merge_variables', 'python_service_systemd_service_options_', pattern_type='prefix') | combine({'User': python_service_user_info.name, 'Group': python_service_user_info.name}) }}"
    systemd_service_enable: "{{ python_service_systemd_enable }}"
    systemd_notify: "{{ python_service_systemd_notify }}"
