---

- name: "Load OS dependent variables"
  ansible.builtin.include_vars:
    file: "{{ ansible_facts['distribution'] | lower }}.yml"
  failed_when: false  # never fail, even if the file does not exist

- name: "Assert that packages to install is a list"
  ansible.builtin.assert:
    that: pipx_install_packages | type_debug == "list"
    msg: "Sorry, due to shitty ansible variable precedence, the packages to install always have to be a list, even if there is only one entry."

- name: "Install pipx"
  ansible.builtin.package:
    name: "{{ pipx_install_dependencies }}"

- name: "Get information about user"
  ansible.builtin.user:
    name: "{{ pipx_install_user }}"
  register: pipx_install_user_info

- name: "Add $HOME/.local/bin to PATH"
  ansible.builtin.lineinfile:
    path: "{{ pipx_install_user_info.home }}/.bashrc"
    insertbefore: "BOF"
    line: "export PATH={{ pipx_install_user_info.home }}/.local/bin:$PATH"
  ignore_errors: "{{ ansible_check_mode }}"

- name: "Install packages and create auto updater entries for user {{ pipx_install_user }}"
  ansible.builtin.include_tasks: install_and_create_auto_updater.yml
  loop: "{{ pipx_install_packages }}"
  loop_control:
    loop_var: pipx_install_package
