---

- name: "Enable and start ssh-agent.service"
  become: true
  become_user: "{{ item }}"
  ansible.builtin.systemd_service:
    name: "ssh-agent.service"
    scope: "user"
    state: started
    enabled: true
  loop: "{{ system_settings_ssh_agent_users }}"
  when: system_settings_ssh_agent_users is defined

- name: "Add SSH_AUTH_SOCK to be available for everyone"
  ansible.builtin.copy:
    dest: "/etc/profile.d/ssh_auth_sock.sh"
    content: |
      export SSH_AUTH_SOCK=$XDG_RUNTIME_DIR/ssh-agent.socket
    mode: 0644
  when: system_settings_ssh_agent_users is defined

- name: "Check if faillock.conf exists"
  ansible.builtin.stat:
    path: "/etc/security/faillock.conf"
  register: system_settings_faillock_conf

- name: "Configure faillock"
  when:
    - system_settings_faillock_conf.stat.exists
    - system_settings_faillock_conf.stat.isreg
  block:
    - name: "Set faillock deny to 10 tries"
      ansible.builtin.lineinfile:
        path: "/etc/security/faillock.conf"
        regexp: "(^|\\W)deny ="
        line: "deny = 10"

    - name: "Set faillock timout to 5 minutes"
      ansible.builtin.lineinfile:
        path: "/etc/security/faillock.conf"
        regexp: "(^|\\W)unlock_time ="
        line: "unlock_time = 300"
