---

- name: "Discover user home for {{ item.user }}"
  ansible.builtin.user:
    name: "{{ item.user }}"
  register: ssh_system_user_info

- name: "Create .ssh directory for {{ item.user }}"
  ansible.builtin.file:
    path: "{{ ssh_system_user_info.home }}/.ssh"
    owner: "{{ ssh_system_user_info.uid }}"
    group: "{{ ssh_system_user_info.group }}"
    mode: "0700"

- name: "Create authorized_keys entries allowing ssh access to the specific user"
  ansible.builtin.copy:
    content: |
      # Ansible Managed file
      {% for key in item.keys_from | map('extract', ssh_keys) | flatten %}
      {{ key }}
      {% endfor %}
    dest: "{{ ssh_system_user_info.home }}/.ssh/authorized_keys"
    owner: "{{ ssh_system_user_info.uid }}"
    group: "{{ ssh_system_user_info.group }}"
    mode: "0600"
