---

- name: "Create user for website"
  ansible.builtin.user:
    name: "{{ ci_managed_webcontent_site.user }}"
    shell: "/usr/bin/nologin"
  register: ci_managed_webcontent_user_info

- name: "Create .ssh directory"
  ansible.builtin.file:
    path: "{{ ci_managed_webcontent_user_info.home }}/.ssh"
    state: directory
    owner: "{{ ci_managed_webcontent_user_info.uid }}"
    group: "{{ ci_managed_webcontent_user_info.group }}"
    mode: "0700"

- name: "Install allowed-commands.sh"
  ansible.builtin.template:
    src: "{{ ci_managed_webcontent_site.allowed_commands_script_template }}"
    dest: "{{ ci_managed_webcontent_user_info.home }}/.ssh/allowed-commands.sh"
    owner: "{{ ci_managed_webcontent_user_info.uid }}"
    group: "{{ ci_managed_webcontent_user_info.group }}"
    mode: "0700"
  register: ci_managed_webcontent_allowed_commands_install_result
  when: "'allowed_commands_script_template' in ci_managed_webcontent_site"

- name: "Set authorized_keys of webcontent user"
  ansible.builtin.copy:
    content: |
      command="{% if 'allowed_commands_script_template' in ci_managed_webcontent_site %}{{ ci_managed_webcontent_user_info.home }}/.ssh/allowed-commands.sh{% else %}/usr/bin/rrsync -wo {{ ci_managed_webcontent_user_info.home }}/www/{% endif %}",restrict {{ ci_managed_webcontent_site.ssh_deploy_public_key }}
    dest: "{{ ci_managed_webcontent_user_info.home }}/.ssh/authorized_keys"
    owner: "{{ ci_managed_webcontent_user_info.uid }}"
    group: "{{ ci_managed_webcontent_user_info.group }}"
    mode: "0600"

- name: "Create deploy directory"
  ansible.builtin.file:
    path: "{{ ci_managed_webcontent_user_info.home }}/www"
    state: directory
    owner: "{{ ci_managed_webcontent_user_info.uid }}"
    group: "{{ ci_managed_webcontent_user_info.group }}"
    mode: "0755"

- name: "Add site config to caddy"
  ansible.builtin.include_role:
    name: "poettig.roles.caddy"
    tasks_from: "add_site_config.yml"
  vars:
    caddy_site_config:
      template: "{{ ci_managed_webcontent_site.caddy_site_config_template }}"
      target_filename: "{{ ci_managed_webcontent_site.fqdn }}"

- name: "Deploy webcontent via GitHub action"
  ansible.builtin.include_role:
    name: "poettig.roles.github_deploy_action"
  vars:
    github_deploy_action_sentinel_file: "{{ ci_managed_webcontent_site.deploy_sentinel_file }}"
    github_deploy_action_repo_path: "{{ ci_managed_webcontent_site.github_repo_path }}"
    github_deploy_action_access_token: "{{ ci_managed_webcontent_site.deploy_repo_access_token }}"
    github_deploy_action_body:
      event_type: "ansible-{{ ci_managed_webcontent_site.deploy_environment }}"
      client_payload:
        branch: "{{ ci_managed_webcontent_site.deploy_branch }}"
